### ISSUE TITLE
httpx in version 0.28+ is not supported for jenkins-pysdk version 1.4.3

### ISSUE THREAD

**Issue by marcopacurariu3** [KnownZero/JenkinsPythonSDK#39]
**Describe the bug**
Jenkins-pysdk it is not working with httpx in version 0.28+, more specifically when calling the JenkinsClient() constructor.

**To Reproduce**
Try to create a new JenkinsClient() object. It will fail because:

/virtualenv/lib/python3.11/site-packages/jenkins_pysdk/core.py", line 145, in _send_http
    with Client(verify=self.verify,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

In newer httpx versions (0.28+), the Client() does not support the proxies field anymore. 
Httpx library: [https://pypi.org/project/httpx/](url)

**Expected behavior**
The JenkinsClient() works with httpx 0.28+.

**Additional context**

**Comment by KnownZero** [comment]
Hi there,

Thanks for spotting this.

It was removed in 0.28:
"0.28.0 (28th November, 2024)"
"The deprecated proxies argument has now been removed."

Will update the code soon.

**Comment by marcopacurariu3** [comment]
Great, thanks a lot!

**Comment by KnownZero** [comment]
https://github.com/KnownZero/JenkinsPythonSDK/pull/40

**Comment by marcopacurariu3** [comment]
Thank you!
